// Generated by scripts/generate_engine_catalog.py. Do not edit.
class EnginePresetInfo {
  const EnginePresetInfo(this.id, this.name, this.maxRpm);
  final String id, name;
  final double maxRpm;
}

const enginePresets = <EnginePresetInfo>[
  EnginePresetInfo("generic", "RevEV \u00b7 Generic 2.0 L I4", 8000),
  EnginePresetInfo(
    "porsche/911_carrera_32",
    "Porsche 911 Carrera 3.2 (approx.)",
    8000,
  ),
  EnginePresetInfo(
    "porsche/911_turbo_33",
    "Porsche 911 Turbo 3.3 (approx.)",
    8000,
  ),
  EnginePresetInfo(
    "atg-video-1/05_honda_vtec",
    "Honda B18C5 [VTEC, I4]",
    12000,
  ),
  EnginePresetInfo(
    "atg-video-2/02_subaru_ej25_uh",
    "Subaru EJ25 \u00b7 Unequal headers",
    8000,
  ),
  EnginePresetInfo("atg-video-2/07_gm_ls", "GM LS", 8000),
  EnginePresetInfo("atg-video-2/08_ferrari_f136_v8", "Ferrari F136", 12000),
  EnginePresetInfo("atg-video-2/03_2jz", "2JZ [I6]", 8000),
  EnginePresetInfo("atg-video-2/10_lfa_v10", "1LR-GUE [V10]", 12000),
];
