// Generated by scripts/generate_engine_catalog.py. Do not edit.
class EnginePresetInfo {
  const EnginePresetInfo(
    this.id,
    this.name,
    this.maxRpm, {
    this.isTurbo = false,
    this.gearCount = 5,
    this.gearRatios = const [3.5, 2.06, 1.41, 1.07, 0.86],
    this.finalDrive = 3.44,
  });
  final String id, name;
  final double maxRpm;
  final bool isTurbo;
  final int gearCount;
  final List<double> gearRatios;
  final double finalDrive;
}

const enginePresets = <EnginePresetInfo>[
  EnginePresetInfo(
    "porsche/911_carrera_32",
    "Porsche 911 Carrera 3.2 (approx.)",
    8000,
    gearCount: 5,
    gearRatios: [3.5, 2.06, 1.41, 1.07, 0.86],
    finalDrive: 3.44,
  ),
  EnginePresetInfo(
    "porsche/911_turbo_33",
    "Porsche 911 Turbo 3.3 (approx.)",
    8000,
    isTurbo: true,
    gearCount: 4,
    gearRatios: [3.15, 1.79, 1.21, 0.89],
    finalDrive: 3.44,
  ),
  EnginePresetInfo(
    "atg-video-1/05_honda_vtec",
    "Honda B18C5 [VTEC, I4]",
    12000,
    gearCount: 5,
    gearRatios: [3.23, 2.11, 1.46, 1.11, 0.85],
    finalDrive: 4.4,
  ),
  EnginePresetInfo(
    "atg-video-2/02_subaru_ej25_uh",
    "Subaru EJ25 \u00b7 Unequal headers",
    8000,
    gearCount: 6,
    gearRatios: [3.64, 2.38, 1.76, 1.35, 1.06, 0.83],
    finalDrive: 3.9,
  ),
  EnginePresetInfo(
    "atg-video-2/07_gm_ls",
    "GM LS",
    8000,
    gearCount: 6,
    gearRatios: [2.66, 1.78, 1.3, 1.0, 0.74, 0.5],
    finalDrive: 3.42,
  ),
  EnginePresetInfo(
    "atg-video-2/08_ferrari_f136_v8",
    "Ferrari F136",
    12000,
    gearCount: 7,
    gearRatios: [3.08, 2.19, 1.63, 1.29, 1.03, 0.84, 0.68],
    finalDrive: 4.5,
  ),
  EnginePresetInfo(
    "atg-video-2/03_2jz",
    "2JZ [I6]",
    8000,
    isTurbo: true,
    gearCount: 6,
    gearRatios: [3.83, 2.36, 1.69, 1.31, 1.0, 0.79],
    finalDrive: 3.27,
  ),
  EnginePresetInfo(
    "atg-video-2/10_lfa_v10",
    "1LR-GUE [V10]",
    12000,
    gearCount: 6,
    gearRatios: [3.23, 2.19, 1.61, 1.26, 1.03, 0.8],
    finalDrive: 3.45,
  ),
];
