"""Generate both platform catalogs from the bundled, reviewed allowlist."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'packages/revev_engine'
catalog = json.loads((ROOT / 'assets/engine-sim/catalog.json').read_text())
assert len({p['id'] for p in catalog}) == len(catalog)
assert len({p['name'] for p in catalog}) == len(catalog)
for preset in catalog:
    if preset['entry']:
        assert (ROOT / 'assets/engine-sim' / preset['entry']).is_file()

quote = lambda value: json.dumps(value, ensure_ascii=True)
c_ident = lambda s: re.sub(r'[^a-zA-Z0-9_]', '_', s)

native = '''// Generated by scripts/generate_engine_catalog.py. Do not edit.
#pragma once
#include <string>
#include <stdexcept>
struct PresetEntry {
    const char *id;
    const char *name;
    const char *entry;
    bool isTurbo;
    int gearCount;
    const double *gearRatios;
    double finalDrive;
};
'''
for p in catalog:
    var_name = 'ratios_' + c_ident(p['id'])
    ratios_str = ', '.join(str(r) for r in p.get('gearRatios', [3.5, 2.06, 1.41, 1.07, 0.86]))
    native += f'inline constexpr double {var_name}[] = {{{ratios_str}}};\n'

native += '\ninline constexpr PresetEntry enginePresets[] = {\n'
for p in catalog:
    var_name = 'ratios_' + c_ident(p['id'])
    gear_count = p.get('gearCount', 5)
    final_drive = p.get('finalDrive', 3.44)
    native += '    {' + ', '.join(quote(p[k] or '') for k in ('id', 'name', 'entry')) + ', ' + \
              ('true' if p.get('turbo') else 'false') + f', {gear_count}, {var_name}, {final_drive}' + '},\n'
native += '''};
inline const PresetEntry &getPreset(const std::string &id) {
    for (const auto &preset : enginePresets) if (id == preset.id) return preset;
    throw std::invalid_argument("Unknown bundled engine");
}
inline std::string presetEntry(const std::string &id) {
    return getPreset(id).entry;
}
inline bool presetIsTurbo(const std::string &id) {
    for (const auto &preset : enginePresets) if (id == preset.id) return preset.isTurbo;
    return false;
}
'''
(ROOT / 'native/preset_catalog.h').write_text(native, encoding='utf-8')

dart = '''// Generated by scripts/generate_engine_catalog.py. Do not edit.
class EnginePresetInfo {
  const EnginePresetInfo(
    this.id,
    this.name,
    this.maxRpm, {
    this.isTurbo = false,
    this.gearCount = 5,
    this.gearRatios = const [3.5, 2.06, 1.41, 1.07, 0.86],
    this.finalDrive = 3.44,
  });
  final String id, name;
  final double maxRpm;
  final bool isTurbo;
  final int gearCount;
  final List<double> gearRatios;
  final double finalDrive;
}

const enginePresets = <EnginePresetInfo>[
'''
for p in catalog:
    gear_count = p.get('gearCount', 5)
    ratios_list = p.get('gearRatios', [3.5, 2.06, 1.41, 1.07, 0.86])
    final_drive = p.get('finalDrive', 3.44)
    dart += '  EnginePresetInfo(\n    ' + quote(p['id']) + ',\n    ' + quote(p['name']) + ',\n    ' + str(p['maxRpm']) + ',\n'
    if p.get('turbo'):
        dart += '    isTurbo: true,\n'
    dart += f'    gearCount: {gear_count},\n'
    dart += f'    gearRatios: {ratios_list},\n'
    dart += f'    finalDrive: {final_drive},\n'
    dart += '  ),\n'
dart += '];\n'
(ROOT / 'lib/engine_presets.dart').write_text(dart, encoding='utf-8')
