"""Generate both platform catalogs from the bundled, reviewed allowlist."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'packages/revev_engine'
catalog = json.loads((ROOT / 'assets/engine-sim/catalog.json').read_text())
assert len({p['id'] for p in catalog}) == len(catalog)
assert len({p['name'] for p in catalog}) == len(catalog)
for preset in catalog:
    if preset['entry']:
        assert (ROOT / 'assets/engine-sim' / preset['entry']).is_file()

quote = lambda value: json.dumps(value, ensure_ascii=True)
native = '''// Generated by scripts/generate_engine_catalog.py. Do not edit.
#pragma once
#include <string>
#include <stdexcept>
struct PresetEntry { const char *id; const char *name; const char *entry; bool isTurbo; };
inline constexpr PresetEntry enginePresets[] = {
'''
native += ''.join('    {' + ', '.join(quote(p[k] or '') for k in ('id', 'name', 'entry')) + ', ' + ('true' if p.get('turbo') else 'false') + '},\n' for p in catalog)
native += '''};
inline std::string presetEntry(const std::string &id) {
    for (const auto &preset : enginePresets) if (id == preset.id) return preset.entry;
    throw std::invalid_argument("Unknown bundled engine");
}
inline bool presetIsTurbo(const std::string &id) {
    for (const auto &preset : enginePresets) if (id == preset.id) return preset.isTurbo;
    return false;
}
'''
(ROOT / 'native/preset_catalog.h').write_text(native, encoding='utf-8')
dart = '''// Generated by scripts/generate_engine_catalog.py. Do not edit.
class EnginePresetInfo {
  const EnginePresetInfo(this.id, this.name, this.maxRpm, {this.isTurbo = false});
  final String id, name;
  final double maxRpm;
  final bool isTurbo;
}

const enginePresets = <EnginePresetInfo>[
'''
dart += ''.join('  EnginePresetInfo(\n    ' + quote(p['id']) + ',\n    ' + quote(p['name']) + ',\n    ' + str(p['maxRpm']) + ',\n' + ('    isTurbo: true,\n' if p.get('turbo') else '') + '  ),\n' for p in catalog)
dart += '];\n'
(ROOT / 'lib/engine_presets.dart').write_text(dart, encoding='utf-8')
